// proto2mysql 自带的建表选项定义。
//
// 用法：在你的 .proto 里 import 本文件，然后在 message / field 上声明表配置，
// 运行时 RegisterTable 会自动读取，无需在 Go 代码里传 TableOption：
//
//	import "proto2mysql_option.proto";
//
//	message user {
//	  option (proto2mysql.table_name)         = "user";
//	  option (proto2mysql.primary_key)        = "id";           // 逗号分隔 = 联合主键
//	  option (proto2mysql.auto_increment_key) = "id";
//	  option (proto2mysql.index)              = "last_login";   // 分号分隔多个索引；索引内逗号分隔 = 联合索引
//	  option (proto2mysql.unique_key)         = "email";        // 逗号分隔 = 联合唯一键
//
//	  uint64 id = 1;
//	  string email = 2;
//	  string display_name = 3 [(proto2mysql.nullable) = true];  // 该列允许为 NULL
//	  uint64 last_login = 4;
//	}
//
// 兼容性说明：message 级选项的扩展字段号与 github.com/luyuancpp/protooption 的
// OptionTableName(500001)/OptionPrimaryKey(500002)/OptionAutoIncrementKey(500006)/
// OptionIndex(500011)/OptionUniqueKey(500012) 完全一致，运行时按字段号反射读取，
// 两套定义任选其一即可。注意：同一个二进制里不要同时链接两套定义的生成代码
// （扩展字段号相同会导致 protoregistry 注册冲突）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto2mysql_option.proto

package pbopt

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_proto2mysql_option_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500001,
		Name:          "proto2mysql.table_name",
		Tag:           "bytes,500001,opt,name=table_name",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500002,
		Name:          "proto2mysql.primary_key",
		Tag:           "bytes,500002,opt,name=primary_key",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500006,
		Name:          "proto2mysql.auto_increment_key",
		Tag:           "bytes,500006,opt,name=auto_increment_key",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500011,
		Name:          "proto2mysql.index",
		Tag:           "bytes,500011,opt,name=index",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         500012,
		Name:          "proto2mysql.unique_key",
		Tag:           "bytes,500012,opt,name=unique_key",
		Filename:      "proto2mysql_option.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         600100,
		Name:          "proto2mysql.nullable",
		Tag:           "varint,600100,opt,name=nullable",
		Filename:      "proto2mysql_option.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// 表名（必填：声明了才视为一张表）
	//
	// optional string table_name = 500001;
	E_TableName = &file_proto2mysql_option_proto_extTypes[0]
	// 主键，逗号分隔 = 联合主键，如 "user_id,provider"
	//
	// optional string primary_key = 500002;
	E_PrimaryKey = &file_proto2mysql_option_proto_extTypes[1]
	// 自增字段名
	//
	// optional string auto_increment_key = 500006;
	E_AutoIncrementKey = &file_proto2mysql_option_proto_extTypes[2]
	// 普通索引：分号分隔多个索引，每个索引内逗号分隔 = 联合索引
	// 如 "player_id;zone_id,created_at"
	//
	// optional string index = 500011;
	E_Index = &file_proto2mysql_option_proto_extTypes[3]
	// 唯一键，逗号分隔 = 联合唯一键，如 "provider,provider_id"
	//
	// optional string unique_key = 500012;
	E_UniqueKey = &file_proto2mysql_option_proto_extTypes[4]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// 该字段对应的列允许为 NULL（默认 NOT NULL）
	//
	// optional bool nullable = 600100;
	E_Nullable = &file_proto2mysql_option_proto_extTypes[5]
)

var File_proto2mysql_option_proto protoreflect.FileDescriptor

const file_proto2mysql_option_proto_rawDesc = "" +
	"\n" +
	"\x18proto2mysql_option.proto\x12\vproto2mysql\x1a google/protobuf/descriptor.proto:C\n" +
	"\n" +
	"table_name\x12\x1f.google.protobuf.MessageOptions\x18\xa1\xc2\x1e \x01(\tR\ttableName\x88\x01\x01:E\n" +
	"\vprimary_key\x12\x1f.google.protobuf.MessageOptions\x18\xa2\xc2\x1e \x01(\tR\n" +
	"primaryKey\x88\x01\x01:R\n" +
	"\x12auto_increment_key\x12\x1f.google.protobuf.MessageOptions\x18\xa6\xc2\x1e \x01(\tR\x10autoIncrementKey\x88\x01\x01::\n" +
	"\x05index\x12\x1f.google.protobuf.MessageOptions\x18\xab\xc2\x1e \x01(\tR\x05index\x88\x01\x01:C\n" +
	"\n" +
	"unique_key\x12\x1f.google.protobuf.MessageOptions\x18\xac\xc2\x1e \x01(\tR\tuniqueKey\x88\x01\x01:>\n" +
	"\bnullable\x12\x1d.google.protobuf.FieldOptions\x18\xa4\xd0$ \x01(\bR\bnullable\x88\x01\x01B.Z,github.com/luyuancpp/proto2mysql/pbopt;pboptb\x06proto3"

var file_proto2mysql_option_proto_goTypes = []any{
	(*descriptorpb.MessageOptions)(nil), // 0: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 1: google.protobuf.FieldOptions
}
var file_proto2mysql_option_proto_depIdxs = []int32{
	0, // 0: proto2mysql.table_name:extendee -> google.protobuf.MessageOptions
	0, // 1: proto2mysql.primary_key:extendee -> google.protobuf.MessageOptions
	0, // 2: proto2mysql.auto_increment_key:extendee -> google.protobuf.MessageOptions
	0, // 3: proto2mysql.index:extendee -> google.protobuf.MessageOptions
	0, // 4: proto2mysql.unique_key:extendee -> google.protobuf.MessageOptions
	1, // 5: proto2mysql.nullable:extendee -> google.protobuf.FieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	0, // [0:6] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto2mysql_option_proto_init() }
func file_proto2mysql_option_proto_init() {
	if File_proto2mysql_option_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto2mysql_option_proto_rawDesc), len(file_proto2mysql_option_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 6,
			NumServices:   0,
		},
		GoTypes:           file_proto2mysql_option_proto_goTypes,
		DependencyIndexes: file_proto2mysql_option_proto_depIdxs,
		ExtensionInfos:    file_proto2mysql_option_proto_extTypes,
	}.Build()
	File_proto2mysql_option_proto = out.File
	file_proto2mysql_option_proto_goTypes = nil
	file_proto2mysql_option_proto_depIdxs = nil
}
