// 仅供本仓库测试使用的示例消息，覆盖表注册、缓存和 CRUD 等场景。
// 建表元数据使用 proto/proto2mysql_option.proto 中的选项定义。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: testpb.proto

package testpb

import (
	_ "github.com/luyuancpp/proto2mysql/pbopt"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_testpb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{0}
}

func (x *Player) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GolangTest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	GroupId       uint32                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Player        *Player                `protobuf:"bytes,5,opt,name=player,proto3" json:"player,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,6,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolangTest) Reset() {
	*x = GolangTest{}
	mi := &file_testpb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolangTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolangTest) ProtoMessage() {}

func (x *GolangTest) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolangTest.ProtoReflect.Descriptor instead.
func (*GolangTest) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{1}
}

func (x *GolangTest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GolangTest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GolangTest) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GolangTest) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GolangTest) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GolangTest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GolangTestList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestList      []*GolangTest          `protobuf:"bytes,1,rep,name=test_list,json=testList,proto3" json:"test_list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolangTestList) Reset() {
	*x = GolangTestList{}
	mi := &file_testpb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolangTestList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolangTestList) ProtoMessage() {}

func (x *GolangTestList) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolangTestList.ProtoReflect.Descriptor instead.
func (*GolangTestList) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{2}
}

func (x *GolangTestList) GetTestList() []*GolangTest {
	if x != nil {
		return x.TestList
	}
	return nil
}

// 新增表1：结构类似，增加一个额外字段
type GolangTest1 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	GroupId       uint32                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Player        *Player                `protobuf:"bytes,5,opt,name=player,proto3" json:"player,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,6,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,7,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolangTest1) Reset() {
	*x = GolangTest1{}
	mi := &file_testpb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolangTest1) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolangTest1) ProtoMessage() {}

func (x *GolangTest1) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolangTest1.ProtoReflect.Descriptor instead.
func (*GolangTest1) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{3}
}

func (x *GolangTest1) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GolangTest1) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GolangTest1) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GolangTest1) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GolangTest1) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GolangTest1) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GolangTest1) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

// 新增表2：结构类似，port 改为 uint64
type GolangTest2 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint64                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	GroupId       uint32                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Player        *Player                `protobuf:"bytes,5,opt,name=player,proto3" json:"player,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,6,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ExtraInfo     string                 `protobuf:"bytes,7,opt,name=extra_info,json=extraInfo,proto3" json:"extra_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolangTest2) Reset() {
	*x = GolangTest2{}
	mi := &file_testpb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolangTest2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolangTest2) ProtoMessage() {}

func (x *GolangTest2) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolangTest2.ProtoReflect.Descriptor instead.
func (*GolangTest2) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{4}
}

func (x *GolangTest2) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GolangTest2) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GolangTest2) GetPort() uint64 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GolangTest2) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GolangTest2) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GolangTest2) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GolangTest2) GetExtraInfo() string {
	if x != nil {
		return x.ExtraInfo
	}
	return ""
}

// 新增表3：结构类似，增加嵌套 player 字段
type GolangTest3 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	GroupId       uint32                 `protobuf:"varint,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Player        *Player                `protobuf:"bytes,5,opt,name=player,proto3" json:"player,omitempty"`
	PlayerId      uint64                 `protobuf:"varint,6,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ExtraPlayer   *Player                `protobuf:"bytes,7,opt,name=extra_player,json=extraPlayer,proto3" json:"extra_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GolangTest3) Reset() {
	*x = GolangTest3{}
	mi := &file_testpb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GolangTest3) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GolangTest3) ProtoMessage() {}

func (x *GolangTest3) ProtoReflect() protoreflect.Message {
	mi := &file_testpb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GolangTest3.ProtoReflect.Descriptor instead.
func (*GolangTest3) Descriptor() ([]byte, []int) {
	return file_testpb_proto_rawDescGZIP(), []int{5}
}

func (x *GolangTest3) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GolangTest3) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GolangTest3) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *GolangTest3) GetGroupId() uint32 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GolangTest3) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *GolangTest3) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *GolangTest3) GetExtraPlayer() *Player {
	if x != nil {
		return x.ExtraPlayer
	}
	return nil
}

var File_testpb_proto protoreflect.FileDescriptor

const file_testpb_proto_rawDesc = "" +
	"\n" +
	"\ftestpb.proto\x1a\x18proto2mysql_option.proto\"9\n" +
	"\x06player\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xba\x01\n" +
	"\vgolang_test\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\rR\agroupId\x12\x1f\n" +
	"\x06player\x18\x05 \x01(\v2\a.playerR\x06player\x12\x1b\n" +
	"\tplayer_id\x18\x06 \x01(\x04R\bplayerId:\x1e\x8a\x92\xf4\x01\vgolang_test\x92\x92\xf4\x01\x02id\xb2\x92\xf4\x01\x02id\"=\n" +
	"\x10golang_test_list\x12)\n" +
	"\ttest_list\x18\x01 \x03(\v2\f.golang_testR\btestList\"\xdb\x01\n" +
	"\fgolang_test1\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\rR\agroupId\x12\x1f\n" +
	"\x06player\x18\x05 \x01(\v2\a.playerR\x06player\x12\x1b\n" +
	"\tplayer_id\x18\x06 \x01(\x04R\bplayerId\x12\x1d\n" +
	"\n" +
	"extra_info\x18\a \x01(\tR\textraInfo:\x1f\x8a\x92\xf4\x01\fgolang_test1\x92\x92\xf4\x01\x02id\xb2\x92\xf4\x01\x02id\"\xdb\x01\n" +
	"\fgolang_test2\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x04R\x04port\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\rR\agroupId\x12\x1f\n" +
	"\x06player\x18\x05 \x01(\v2\a.playerR\x06player\x12\x1b\n" +
	"\tplayer_id\x18\x06 \x01(\x04R\bplayerId\x12\x1d\n" +
	"\n" +
	"extra_info\x18\a \x01(\tR\textraInfo:\x1f\x8a\x92\xf4\x01\fgolang_test2\x92\x92\xf4\x01\x02id\xb2\x92\xf4\x01\x02id\"\xe8\x01\n" +
	"\fgolang_test3\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\rR\agroupId\x12\x1f\n" +
	"\x06player\x18\x05 \x01(\v2\a.playerR\x06player\x12\x1b\n" +
	"\tplayer_id\x18\x06 \x01(\x04R\bplayerId\x12*\n" +
	"\fextra_player\x18\a \x01(\v2\a.playerR\vextraPlayer:\x1f\x8a\x92\xf4\x01\fgolang_test3\x92\x92\xf4\x01\x02id\xb2\x92\xf4\x01\x02idB>\x80\x92\xf4\x01\x01Z7github.com/luyuancpp/proto2mysql/internal/testpb;testpbb\x06proto3"

var (
	file_testpb_proto_rawDescOnce sync.Once
	file_testpb_proto_rawDescData []byte
)

func file_testpb_proto_rawDescGZIP() []byte {
	file_testpb_proto_rawDescOnce.Do(func() {
		file_testpb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testpb_proto_rawDesc), len(file_testpb_proto_rawDesc)))
	})
	return file_testpb_proto_rawDescData
}

var file_testpb_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_testpb_proto_goTypes = []any{
	(*Player)(nil),         // 0: player
	(*GolangTest)(nil),     // 1: golang_test
	(*GolangTestList)(nil), // 2: golang_test_list
	(*GolangTest1)(nil),    // 3: golang_test1
	(*GolangTest2)(nil),    // 4: golang_test2
	(*GolangTest3)(nil),    // 5: golang_test3
}
var file_testpb_proto_depIdxs = []int32{
	0, // 0: golang_test.player:type_name -> player
	1, // 1: golang_test_list.test_list:type_name -> golang_test
	0, // 2: golang_test1.player:type_name -> player
	0, // 3: golang_test2.player:type_name -> player
	0, // 4: golang_test3.player:type_name -> player
	0, // 5: golang_test3.extra_player:type_name -> player
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_testpb_proto_init() }
func file_testpb_proto_init() {
	if File_testpb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testpb_proto_rawDesc), len(file_testpb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testpb_proto_goTypes,
		DependencyIndexes: file_testpb_proto_depIdxs,
		MessageInfos:      file_testpb_proto_msgTypes,
	}.Build()
	File_testpb_proto = out.File
	file_testpb_proto_goTypes = nil
	file_testpb_proto_depIdxs = nil
}
